### ISSUE TITLE
Optimize Lind Performance

### ISSUE THREAD

**Issue by rennergade** [Lind-Project/lind_project#102]
I'm creating this issue to be an overview of the work to be done in improving Lind's overall performance, which is important for our results. There are a number of open issues

- [x] [Fix Fork ](https://github.com/Lind-Project/lind_project/issues/67)

- [x] [Remove fstat from Open](https://github.com/Lind-Project/lind_project/issues/98)

- [x] [Re-work directory caching for Open (currently uses stat)](https://github.com/Lind-Project/lind_project/issues/98)

- [x] [Get rid of extra fstat in mmap](https://github.com/Lind-Project/lind_project/issues/98)

- [ ] [Improve efficiency of persist_metadata](https://github.com/Lind-Project/lind_project/issues/97)

- [x] [Remove overhead from locks in SafePOSIX](https://github.com/Lind-Project/lind_project/issues/56)

- [x] [Remove overhead from closure in SafePOSIX](https://github.com/Lind-Project/lind_project/issues/56)

- [ ] [Improve efficiency of pack_struct](https://github.com/Lind-Project/lind_project/issues/117)

**Comment by rennergade** [comment]
**Locks**

Changing locks from the namespace.py repy protocol to a monkey patch reduces total syscall time by ~25%. Interestingly enough, changing the locks to a no-op results in basically the same performance increase, showing that all the overhead there was from the namespace wrapper.

I'm going to try and layout the locks in a more efficient fashion to get some futher performance gains.

**Comment by rennergade** [comment]
Changing the lock infrastructure was able to reduce total time slightly by getting rid of the global per cage lock, but increased time in syscall implementations by adding some extra locks that were needed. This is slightly a wash, as the time improvements are <<< than from just changing to the monkey-patched locks, but the changes I made give better consistency.

**Comment by rennergade** [comment]
Per meeting conversation, it looks like best way to get rid of open() overhead is to remove nacl desc's, per: https://github.com/Lind-Project/lind_project/issues/18

**Comment by rennergade** [comment]
Thanks to @jesings the closure time has been removed significantly. This looks like ~15% performance increase in SafePOSIX.

[PR here.](https://github.com/Lind-Project/nacl_repy/pull/37)

**Comment by rennergade** [comment]
This issue isn't really pertinent anymore due to the RustPOSIX change. I'm sure we'll still need to tweak efficiency issues but will open individual issues on those as they apply.
